; homez.g
; called to home the Z axis
;Set Extrude 0
T0
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
G91              ; relative positioning
G1 H2 Z5 F10800  ; lift Z relative to current position
G1 X100 Y100 F5000
G30
G29 S1
; Uncomment the following lines to lift Z after probing
;G91             ; relative positioning
;G1 Z5 F180      ; lift Z relative to current position
;G90             ; absolute positioning

