; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
G91               ; relative positioning
;G1 H2 Z5 F10800   ; lift Z relative to current position
G1 H1 X-235 F3800 ; move quickly to X axis endstop and stop there (first pass)
G1 H2 X5 F10800   ; go back a few mm
G1 H1 X-235 F360  ; move slowly to X axis endstop once more (second pass)
;G1 H2 Z-5 F10800  ; lower Z again
G90               ; absolute positioning

