; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
G91                     ; relative positioning
G1 H2 Z5 F10800         ; lift Z relative to current position
G1 H1 X-235 Y-215 F3800 ; move quickly to X and Y axis endstops and stop there (first pass)
G1 H2 X5 Y5 F10800      ; go back a few mm
G1 H1 X-235 Y-215 F360  ; move slowly to X and Y axis endstops once more (second pass)         
G90                     ; absolute positioning
G1 X100 Y100 F4000
G30
;G92 Z200                ; set Z position to axis maximum (you may want to adjust this)

; Uncomment the following lines to lift Z after probing
;G91                    ; relative positioning
;G1 Z5 F180             ; lift Z relative to current position
;G90                    ; absolute positioning


