; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
; Wait for set temperatures to be reached
M116 P0
;M591 D0 S1
;M118 S"TPOST0"
T1
M703