; homex.g
; called to home the X axis
;
M913 X100
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
G91                ; relative positioning
G1 H1 Z5 F6000     ; lift Z relative to current position
G1 H1 Y60 F6000
G1 H1 X-1205 F10000 ; move quickly to X axis endstop and stop there (first pass)
G1 X5 F6000     ; go back a few mm
G1 H1 X-1205 F1000  ; move slowly to X axis endstop once more (second pass)
G1 H1 Z-5 F6000    ; lower Z again
G90                ; absolute positioning

M913 X100

