; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
T-1
M561 ; clear any bed transform
G29 S2  ; probe the bed and enable compensation
G28
while true
    G4 P400
	G30 P0 X30 Y560 Z-99999
	G4 P400
	G30 P1 X550 Y30 Z-99999 
	G4 P400
	G30 P2 X950 Y560 Z-99999 S3
    if abs(move.calibration.initial.deviation) < 0.01 || iterations > 3
        break