; homez.g
; called to home the Z axis
;
;M84 E0:1
;M280 P0 S160 I1
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
;G91                ; relative positioning
;G1 H2 Z5 F6000     ; lift Z relative to current position
;G90                ; absolute positioning
;G1 X500 Y275 F6000 ; go to first probe point
;G4 P500
;G30                ; home Z by probing the bed 
;G29 S1
; Uncomment the following lines to lift Z after probing
;G91               ; relative positioning
;G1 Z5 F100        ; lift Z relative to current position
;G90               ; absolute positioning
T-1
;G91              ; relative positioning
;G1 H1 Z215 F1800 ; move Z toward Z max until the endstop is triggered (fast)
;G1 Z-20          ; backoff a bit
;G1 H1 Z25 F600   ; move Z toward Z max until the endstop is triggered (slow)
;G92 Z210         ; set Z position to match actual Z position when endstop was triggered
;G91             ; relative mode
;G1 H3 Z530 F800 ; move Z towards the switch until it triggers
;G1 H1 Z700 F1000 ; move Z towards the switch until it triggers
;G90             ; back to absolute mode
G1 X500 Y300 F4500
G30
