; homeall.g
; called to home all axes
;T0
;M84 E0:1
;M280 P0 S160 I1
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
;G91                      ; relative positioning
;G1 H1 Z5 F6000           ; lift Z relative to current position
;G1 H1 X-1005 Y-565 F1800 ; move quickly to X and Y axis endstops and stop there (first pass)
;G1 H2 X5 Y5 F6000        ; go back a few mm
;G1 H1 X-1005 Y-565 F360  ; move slowly to X and Y axis endstops once more (second pass)
;G90                      ; absolute positioning
;G1 X500 Y275 F6000       ; go to first bed probe point and home Z
;G4 P500
;G30                      ; home Z by probing the bed
; Uncomment the following lines to lift Z after probing
;G91                     ; relative positioning
;G1 Z5 F100              ; lift Z relative to current position
;G90                     ; absolute positioning

M98 P"homey.g"
M98 P"homex.g"
T-1
M18 C
M98 P"homez.g"
