; tpre0.g
; called before tool 0 is selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
if move.axes[0].homed == false && move.axes[1].homed == false
    G28 Y
	G28 X
M591 D0 S1
M591 D1 S0
;M118 S"TPRE0"
M564 H0 S0
G0 C0 F10000
G0 X{global.xPT1Position} Y{move.axes[1].min} F8000
G0 Y{move.axes[1].min - global.yPT1Position} F8000
M400
G0 C60 F10000
M400
G0 Y0
M564 H0 S1
G10 P1