; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
M561 ; clear any bed transform
;G29  ; probe the bed and enable compensation

G28
G4 P400
G30 P0 X500 Y450 Z-99999
G4 P400
G30 P1 X950 Y150 Z-99999
G4 P400
G30 P2 X150 Y150 Z-99999 S3


