; tpre0.g
; called before tool 0 is selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
G4 P400
M591 D0 S1
;M118 S"TPRE0"