ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=IT

network={
    ssid="TIM-23864671"
    psk="0JWyThpTMdUzcaTkM5gBFZHz"
    key_mgmt=WPA-PSK
}

network={
    ssid="iPhone di Angelo"
    psk="asdasdasd"
    key_mgmt=WPA-PSK
}

network={
    ssid="FastParts_Printer"
    psk="Fabbrix&FastParts"
    key_mgmt=WPA-PSK
}

network={
    ssid="Linkem_27B7EC"
    psk="f38E8yRs"
    key_mgmt=WPA-PSK
}

#network={
#    ssid="Linkem5GHz_E9C8A9"
#    psk="z641yy4/"
#    key_mgmt=WPA-PSK
#}

network={
    ssid="RedmIndo"
    psk="indolab4k"
    key_mgmt=WPA-PSK
}

network={
    ssid="FabbrixElemento"
    psk="asdasdasd"
    key_mgmt=WPA-PSK
}

network={
    ssid="TIM-29166061"
    psk="1987titapic02"
    key_mgmt=WPA-PSK
}