;Y sensorless
;M915 P71.0 S0 F0 H175 R0
;M915 P72.0 S0 F0 H175 R0
;M574 Y1 S4		
;M913 C70
;G1 H1 Y-900 F2000 ; move quickly to X axis endstop and stop there (first pass)
;G1 C20 F1000     ; go back a few mm
;G1 H1 Y-900 F2000; move slowly to X axis endstop once more (second pass)
;G90                ; absolute positioning
;M913 C100

; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
G91               ; relative positioning
G1 H1 Z5 F6000    ; lift Z relative to current position
G1 H1 Y1000 F4000 ; move quickly to Y axis endstop and stop there (first pass)
G1 Y-5 F6000    ; go back a few mm
G1 H1 Y1000 F1000  ; move slowly to Y axis endstop once more (second pass)
G1 H1 Z-5 F6000   ; lower Z again
G90               ; absolute positioning
