; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
M561 ; clear any bed transform
;G29  ; probe the bed and enable compensation
G28 ; home
G30 P0 X10 Y10 Z-99999  ; probe near an adjusting screw
G30 P1 X180 Y10 Z-99999  ; probe near an adjusting screw
G30 P2 X100 Y180 Z-99999 S3 ; probe near an adjusting screw and report adjustments needed

