; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
;G91                     ; relative positioning
;G1 H1 Z5 F10800         ; lift Z relative to current position
;G1 H1 X-235 Y-235 F1800 ; move quickly to X and Y axis endstops and stop there (first pass)
;G1 H1 X5 Y5 F10800      ; go back a few mm
;G1 H1 X-235 Y-235 F360  ; move slowly to X and Y axis endstops once more (second pass)         
;G90                     ; absolute positioning
;G1 X120 Y120 F1800
;G30
;G1 H1 Z45 F300
;G92 Z200                ; set Z position to axis maximum (you may want to adjust this)

; Uncomment the following lines to lift Z after probing
;G91                    ; relative positioning
;G1 Z5 F180             ; lift Z relative to current position
;G90                    ; absolute positioning


M98 P"homez.g"
G4 S1
M98 P"homey.g"
G4 S1
M98 P"homex.g"
G4 S1