; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
; Wait for set temperatures to be reached
M116 P0

