; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
M84 E0:1
M280 P0 S10 I1; deploy BLTouch
G4 P500