; homex.g
; called to home the X axis
;
M569 P70.0 S0 D2                                       ; driver 70.0 goes forwards (X axis)
M915 P70.0 S0 F0 H190 R0
M574 X1 S3		
M913 X100
M564 H0 S0

; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
G91                ; relative positioning
G1 H1 Z5 F1000     ; lift Z relative to current position
G1 H2 X0.5 F500
G1 H1 X-1205 F3000  ; move slowly to X axis endstop once more (second pass)
G1 H1 Z-5 F1000    ; lower Z again
G90                ; absolute positioning

M569 P70.0 S0 D4                                       ; driver 70.0 goes forwards (Y axis)
M913 X100
