; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
;M591 D0 S0
M118 P0 L2 S"T1 Free"

if (move.axes[0].homed = false || move.axes[1].homed = false)
    G28 Y
	G28 X
    G92 C60
G0 X{global.xPT1Position}  Y{move.axes[1].min} F8000    
M564 H0 S0
G0 X{global.xPT1Position}  Y{move.axes[1].min - global.yPT0Position + 11} F8000
G0 Y{move.axes[1].min - global.yPT1Position} F8000
M400
G0 C0 F6000
M400
G0 Y{-global.yPT0Position + 11}
M400
M564 H0 S1
