; Configuration file for RepRapFirmware on Duet 3 Main Board 6HC
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.3+2 on Thu Mar 28 2024 11:42:04 GMT+0100 (Ora standard dell’Europa centrale)

; General
M550 P"ElementoTC"                           ; set hostname

; Wait a moment for the CAN expansion boards to become available
G4 S2

; Smart Drivers
M569.1 P70.0 T3                          ; driver 70.0 has a magnetic encoder with 5 CPS
M569 P70.0 S0 D2                         ; driver 70.0 goes forwards (X axis)
M569.1 P71.0 T3 E1:2 R100 I0 D0
;M569.1 P71.0 T3                       ; driver 71.0 has a magnetic encoder with 5 CPS
M569 P71.0 S0 D5                         ; driver 71.0 goes forwards (Y axis)
;M569.1 P72.0 T3                      ; driver 72.0 has a magnetic encoder with 5 CPS
M569.1 P72.0 T3 E1:2 R100 I0 D0
M569 P72.0 S0 D5                         ; driver 72.0 goes forwards (Y axis)
M569.1 P73.0 T3                       ; driver 73.0 has a magnetic encoder with 5 CPS
M569 P73.0 S0 D2                         ; driver 73.0 goes forwards (ZL axis)
M569.1 P74.0 T3                       ; driver 74.0 has a magnetic encoder with 5 CPS
M569 P74.0 S0 D2                         ; driver 74.0 goes forwards (Z axis)
M569.1 P75.0 T3                       ; driver 75.0 has a magnetic encoder with 5 CPS
M569 P75.0 S0 D2                         ; driver 75.0 goes forwards (Z axis)
;M569 P121.0 S0 D2                        ; driver 121.0 goes forwards (extruder 0)
;M569 P122.0 S0 D2                        ; driver 122.0 goes forwards (extruder 1)
M569 P0.0 S0 D3 ;V60                          ; driver 122.0 goes forwards (TC)

;Stall Detection
M915 P0.0 S2 F0 H100 R0			        ; Coupler
;M915 P70.0 S2 F0 H100 R0
; Motor Idle Current Reduction
M906 I30                                 ; set motor current idle factor
M84 S30                                  ; set motor current idle timeout

; Closed-Loop Drivers
                     

; Axes C
M584 X70.0 Y71.0:72.0 Z73.0:74.0:75.0 C0.0                           ; set axis mapping
M350 X16 Y16 Z16 C16 I1                         ; configure microstepping with interpolation
M906 X800 Y800 Z1800 C800                           ; set axis driver currents
M92 X100 Y100 Z640 C200                           ; configure steps per mm
M208 X-30:1100 Y-10:640 Z0:650 C0:70                          ; set minimum and maximum axis limits
M566 X900 Y900 Z120 C120000                        ; set maximum instantaneous speed changes (mm/min)
M203 X6000 Y6000 Z4000 C200000                        ; set maximum speeds (mm/min)
M201 X500 Y500 Z500 C40000                         ; set accelerations (mm/s^2)

; Extruders
;M584 E121.0:122.0                        ; set extruder mapping
;M350 E16:16 I1                           ; configure microstepping with interpolation
;M906 E1000:1000                          ; set extruder driver currents
;M92 E1000:1000                             ; configure steps per mm
;M566 E120:120                            ; set maximum instantaneous speed changes (mm/min)
;M203 E10000:10000                          ; set maximum speeds (mm/min)
;M201 E250:250                            ; set accelerations (mm/s^2)

; Kinematics
M669 K0                                  ; configure Cartesian kinematics

; Probes
M558 K0 P11 C"60.i2c.ldc1612" F36000 T36000
M558.2 K0 S16 R136237
G31 X0 Y-31
;M308 A"Chamber" S10 Y"thermistor" P"60.temp0" ; thermistor on coil
M955 P60.0 I20 ; Add accelerometer on SZP with CAN address 120 and specify orientation

; Endstops
M574 X1 P"!io0.in" S1                     ; configure X axis endstop
;M574 X1 S3
M574 Y1 P"!io1.in" S1;+!io2.in" S1                     ; configure Y axis endstop
M574 Z2 P"!io3.in+!io4.in+!io5.in" S1
M574 C1 S3								; Stall detect coupler at low end of its range

; Mesh Bed Compensation
M557 X50:1000 Y100:600 P30:20             ; define grid for mesh bed compensation

; Sensors
M308 S0 P"temp0" Y"thermistor" T50000 A"Heated Bed" ; configure sensor #0
;M308 S1 P"121.temp0" Y"pt1000" A"T0"     ; configure sensor #1
;M308 S2 P"122.temp0" Y"pt1000" A"T1"     ; configure sensor #2
;M308 A"CH" S3 Y"thermistor" P"60.temp0" ; thermistor on coil         ; configure sensor #3

; Heaters
M950 H0 C"out0" T0                       ; create heater #0
M143 H0 P0 T0 C0 S125 A0                 ; configure heater monitor #0 for heater #0
M307 H0 R2.43 D5.5 E1.35 K0.56 B0        ; configure model of heater #0
M950 H1 C"out2" T1                   ; create heater #1
M143 H1 P0 T1 C0 S285 A0                 ; configure heater monitor #0 for heater #1
M307 H1 R2.43 D5.5 E1.35 K0.56 B0        ; configure model of heater #1
M950 H2 C"out3" T2                   ; create heater #2
M143 H2 P0 T1 C0 S285 A0                 ; configure heater monitor #0 for heater #2
M307 H2 R2.43 D5.5 E1.35 K0.56 B0        ; configure model of heater #2
M950 H3 C"out1" T3                       ; create heater #3
M143 H3 P0 T1 C0 S285 A0                 ; configure heater monitor #0 for heater #3
M307 H3 R2.43 D5.5 E1.35 K0.56 B0        ; configure model of heater #3

; Heated beds
M140 P0 H0                               ; configure heated bed #0

; Heated chambers
M141 P1 H3                               ; configure heated chamber #1

; Fans
;M950 F0 C"121.out1"                      ; create fan #0
;M106 P0 C"FT0" S0 L0 X1 B0.1             ; configure fan #0
;M950 F1 C"122.out1"                      ; create fan #1
;M106 P1 C"FT1" S0 L0 X1 B0.1             ; configure fan #1
;M950 F2 C"121.out2"                      ; create fan #2
;M106 P2 C"FNT0" S0 B0.1 H1 T45           ; configure fan #2
;M950 F3 C"122.out2"                      ; create fan #3
;M106 P3 C"FNT1" S0 B0.1 H2 T45           ; configure fan #3

; Led
M950 F3 C"out8"
M106 P3 B300 C"LED" S1
M106 P3 S1
;Fan QC
M950 F4 C"out9"
M106 P4 B300 C"QC" S1
M106 P4 S1


; Trigger TC/0/1
M950 J6 C"!io6.in"
M950 J7 C"!io7.in"
M950 J8 C"!io8.in"
;M581 T2 P6 S1
M581 T3 P7 S1
M581 T4 P8 S1

; Tools
;M563 P0 S"T0" D0 H1 F0                                                          ; create tool #0
;M568 P0 R0 S0                                                                   ; set initial tool #0 active and standby temperatures to 0C
;M591 D0 P3 A1 L25.3 R98:102 C"121.io1.in" E0.2 S2                               ; MFM config
;M563 P1 S"T1" D1 H2 F1                   ; create tool #1
;M568 P1 R0 S0                            ; set initial tool #1 active and standby temperatures to 0C

; Miscellaneous
;T0                                       ; select first tool
if sensors.gpIn[7].value == 1 && sensors.gpIn[8].value == 1
    M118 S"No extruder in printer, please resolve conflict"
elif sensors.gpIn[6].value == 1 && sensors.gpIn[7].value == 1
    M118 S"Extruder T0 on TC"
elif sensors.gpIn[6].value == 1 && sensors.gpIn[8].value == 1
    M118 S"Extruder T1 on TC"

global xPT0Position = 0
global yPT0Position = 0

M950 E0 C"led" T1 U78 Q3000000   ; create a RGB Neopixel LED strip on the LED port and set SPI frequency to 3MHz
M150 E0 R255 U40 B0 S78 P200

; Load Config saved
M501