; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
;M591 D0 S0
G91
G0 F6000
G1 Z1.8
G90
;M118 S"TFREE0"